issue7
side-poject-Deliver/Deliver-project pull request #12
Opened 2023-01-31 17:31 UTC by wucheiwei

半成品order model

2023-01-31 17:40 UTC, Danny3766 approved these changes

2023-01-31 17:46 UTC, timwu0109 requested changes

2023-01-31 17:46 UTC, timwu0109 commented on app/views/orders/show.html.erb
> +      商品名稱：<%=order.product_name%> 數量：<%=order.quantity%>
名稱跟數量記得換行

2023-01-31 17:46 UTC, timwu0109 commented on app/views/orders/show.html.erb
> +  <%=@orders.each do |order|%>
這邊不是用實體變數去用就好了應該不用再跑一次迴圈

2023-01-31 17:46 UTC, timwu0109 commented on app/controllers/orders_controller.rb
> +    @orders = Order.all
show 這邊是不是應該要用. Order.find(params[:id])  這邊應該是看單張訂單裡面的狀況

2023-01-31 17:46 UTC, timwu0109 commented on app/controllers/orders_controller.rb
> +    @order = Order.new(
後面怎麼不用在private 定義的def clean_order 帶到面就好

2023-01-31 17:48 UTC, wucheiwei commented on app/views/orders/show.html.erb
> +      商品名稱：<%=order.product_name%> 數量：<%=order.quantity%>
名稱數量是故意的到時候要顯示在名稱後面

2023-01-31 17:55 UTC, wucheiwei commented on app/controllers/orders_controller.rb
> +    @order = Order.new(
這邊是因為欄位的資料會從其他地方帶進來要看new到時候怎麼處理這個只是先寫

2023-01-31 17:56 UTC, wucheiwei commented on app/views/orders/show.html.erb
> +  <%=@orders.each do |order|%>
已修正

2023-01-31 17:56 UTC, wucheiwei commented on app/controllers/orders_controller.rb
> +    @orders = Order.all
已修正

2023-02-01 00:17 UTC, timwu0109 approved these changes

2023-02-01 00:17 UTC, timwu0109 commented on app/controllers/orders_controller.rb
> +    @order = Order.new(
瞭解瞭解

2023-02-01 00:18 UTC, merged